Fixes #30442 - Update after review

diff --git a/app/views/unattended/provisioning_templates/registration/global_registration.erb b/app/views/unattended/provisioning_templates/registration/global_registration.erb
--- a/app/views/unattended/provisioning_templates/registration/global_registration.erb
+++ b/app/views/unattended/provisioning_templates/registration/global_registration.erb
@@ -5,8 +5,7 @@ model: ProvisioningTemplate
 -%>
 #!/bin/sh
 <%
-    curl_headers = ["-H 'Content-Type: application/json'", "-H 'Accept: application/json'", "-H 'Authorization: Bearer #{@auth_token}'"]
-    curl_vars = { headers: curl_headers, organization: @organization, location: @location, hostgroup: @hostgroup }
+    headers = ['Content-Type: application/json', 'Accept: application/json', "Authorization: Bearer #{@auth_token}"]
 %>
 
 # Template parameters:
@@ -22,16 +21,27 @@ fi
 
 if [ -f /etc/os-release ] ; then
   . /etc/os-release
+else
+    echo "Missing /etc/os-release file!"
+    exit 1
 fi
+
+create_host_curl() {
+  curl --request POST <%= foreman_server_url %>/api/hosts \
+       <%= headers.map{|h| "-H '#{h}'"}.join(' ') %> \
+       -d '{ "host": { "name": "'$(hostname --fqdn)'", "build": "false", "managed": "false"
+       <%= ", \"organization_id\": \"#{@organization.id}\"" if @organization -%>
+       <%= ", \"location_id\": \"#{@location.id}\"" if @location -%>
+       <%= ", \"hostgroup_id\": \"#{@hostgroup.id}\"" if @hostgroup -%>
+       }}'
+}
 
 echo "#"
 echo "# Running registration"
-echo "# Hostname: $HOSTNAME"
-echo "# OS: $NAME"
 echo "#"
 
-if [ $ID = rhel ] ; then
-<% if plugin_present?('katello') %>
+<% if plugin_present?('katello') -%>
+if [ x$ID = xrhel ] || [ x$ID = xcentos ]; then
     CONSUMER_RPM=$(mktemp --suffix .rpm)
 
     curl --insecure --output $CONSUMER_RPM <%= subscription_manager_configuration_url %>
@@ -40,9 +50,9 @@ if [ $ID = rhel ] ; then
     subscription-manager register --org=<%= @organization.label %> --activationkey="sample-key"
 
     rm -f $CONSUMER_RPM
-<% else %>
-    <%= snippet 'create_host_curl', variables: curl_vars %>
-<% end %>
 else
-    <%= snippet 'create_host_curl', variables: curl_vars %>
+    create_host_curl
 fi
+<% else %>
+create_host_curl
+<% end %>
